// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package coop.rchain.models
import coop.rchain.models.BitSetBytesMapper.bitSetBytesMapper
import coop.rchain.models.ParSetTypeMapper.parSetESetTypeMapper
import coop.rchain.models.ParMapTypeMapper.parMapEMapTypeMapper
import coop.rchain.models.BigIntTypeMapper.bigIntBytesTypeMapper
import coop.rchain.models.EqualMDerivation.gen
import coop.rchain.models.EqualMImplicits._

@SerialVersionUID(0L)
final case class ListParWithRandom(
    pars: _root_.scala.Seq[coop.rchain.models.Par] = _root_.scala.Seq.empty,
    randomState: coop.rchain.crypto.hash.Blake2b512Random = coop.rchain.models.ListParWithRandom._typemapper_randomState.toCustom(_root_.com.google.protobuf.ByteString.EMPTY)
    ) extends coop.rchain.models.StacksafeMessage[ListParWithRandom] with scalapb.lenses.Updatable[ListParWithRandom] {
    
    override def equals(x: Any): Boolean = {
    
      import coop.rchain.catscontrib.effect.implicits.sEval
    
     coop.rchain.models.EqualM[coop.rchain.models.ListParWithRandom].equals[cats.Eval](this, x).value
    
    }
    
    override def hashCode(): Int = {
    
      import coop.rchain.catscontrib.effect.implicits.sEval
    
     coop.rchain.models.HashM[coop.rchain.models.ListParWithRandom].hash[cats.Eval](this).value
    
    }
    
    
    def mergeFromM[F[_]: cats.effect.Sync](`_input__`: _root_.com.google.protobuf.CodedInputStream): F[coop.rchain.models.ListParWithRandom] = {
      
      import cats.effect.Sync
      import cats.syntax.all._
      
      Sync[F].defer {
        val __pars = (new _root_.scala.collection.immutable.VectorBuilder[coop.rchain.models.Par] ++= this.pars)
        var __randomState = this.randomState
        var _done__ = false
        
        Sync[F].whileM_ (Sync[F].delay { !_done__ }) {
          for {
            _tag__ <- Sync[F].delay { _input__.readTag() }
            _ <- _tag__ match {
              case 0 => Sync[F].delay { _done__ = true }
              case 10 =>
                for {
                  readValue       <- coop.rchain.models.SafeParser.readMessage(_input__, coop.rchain.models.Par.defaultInstance)
                  customTypeValue =  readValue
                  _               <- Sync[F].delay { __pars += customTypeValue }
                } yield ()
              case 18 =>
                for {
                  readValue       <- Sync[F].delay { _input__.readBytes() }
                  customTypeValue =  coop.rchain.models.ListParWithRandom._typemapper_randomState.toCustom(readValue)
                  _               <- Sync[F].delay { __randomState = customTypeValue }
                } yield ()
            case tag => Sync[F].delay { _input__.skipField(tag) }
            }
          } yield ()
        }
        .map { _ => coop.rchain.models.ListParWithRandom(
          pars = __pars.result(),
          randomState = __randomState
        )}
      }
    }
    
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      pars.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      
      {
        val __value = coop.rchain.models.ListParWithRandom._typemapper_randomState.toBase(randomState)
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(2, __value)
        }
      };
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    
    @transient var _serializedSizeM: coop.rchain.models.Memo[Int] = null
    
    def serializedSizeM: coop.rchain.models.Memo[Int] = synchronized {
      if(_serializedSizeM == null) {
        _serializedSizeM = new coop.rchain.models.Memo(coop.rchain.models.ProtoM.serializedSize(this))
        _serializedSizeM
      } else _serializedSizeM
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      pars.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = coop.rchain.models.ListParWithRandom._typemapper_randomState.toBase(randomState)
        if (!__v.isEmpty) {
          _output__.writeBytes(2, __v)
        }
      };
    }
    def clearPars = copy(pars = _root_.scala.Seq.empty)
    def addPars(__vs: coop.rchain.models.Par *): ListParWithRandom = addAllPars(__vs)
    def addAllPars(__vs: Iterable[coop.rchain.models.Par]): ListParWithRandom = copy(pars = pars ++ __vs)
    def withPars(__v: _root_.scala.Seq[coop.rchain.models.Par]): ListParWithRandom = copy(pars = __v)
    def withRandomState(__v: coop.rchain.crypto.hash.Blake2b512Random): ListParWithRandom = copy(randomState = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => pars
        case 2 => {
          val __t = coop.rchain.models.ListParWithRandom._typemapper_randomState.toBase(randomState)
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(pars.iterator.map(_.toPMessage).toVector)
        case 2 => _root_.scalapb.descriptors.PByteString(coop.rchain.models.ListParWithRandom._typemapper_randomState.toBase(randomState))
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: coop.rchain.models.ListParWithRandom.type = coop.rchain.models.ListParWithRandom
    // @@protoc_insertion_point(GeneratedMessage[ListParWithRandom])
}

object ListParWithRandom extends scalapb.GeneratedMessageCompanion[coop.rchain.models.ListParWithRandom] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[coop.rchain.models.ListParWithRandom] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): coop.rchain.models.ListParWithRandom = {
    val __pars: _root_.scala.collection.immutable.VectorBuilder[coop.rchain.models.Par] = new _root_.scala.collection.immutable.VectorBuilder[coop.rchain.models.Par]
    var __randomState: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __pars += _root_.scalapb.LiteParser.readMessage[coop.rchain.models.Par](_input__)
        case 18 =>
          __randomState = _input__.readBytes()
        case tag => _input__.skipField(tag)
      }
    }
    coop.rchain.models.ListParWithRandom(
        pars = __pars.result(),
        randomState = coop.rchain.models.ListParWithRandom._typemapper_randomState.toCustom(__randomState)
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[coop.rchain.models.ListParWithRandom] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      coop.rchain.models.ListParWithRandom(
        pars = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[coop.rchain.models.Par]]).getOrElse(_root_.scala.Seq.empty),
        randomState = coop.rchain.models.ListParWithRandom._typemapper_randomState.toCustom(__fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY))
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = RhoTypesProto.javaDescriptor.getMessageTypes().get(4)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = RhoTypesProto.scalaDescriptor.messages(4)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = coop.rchain.models.Par
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = coop.rchain.models.ListParWithRandom(
    pars = _root_.scala.Seq.empty,
    randomState = coop.rchain.models.ListParWithRandom._typemapper_randomState.toCustom(_root_.com.google.protobuf.ByteString.EMPTY)
  )
  implicit class ListParWithRandomLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, coop.rchain.models.ListParWithRandom]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, coop.rchain.models.ListParWithRandom](_l) {
    def pars: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[coop.rchain.models.Par]] = field(_.pars)((c_, f_) => c_.copy(pars = f_))
    def randomState: _root_.scalapb.lenses.Lens[UpperPB, coop.rchain.crypto.hash.Blake2b512Random] = field(_.randomState)((c_, f_) => c_.copy(randomState = f_))
  }
  final val PARS_FIELD_NUMBER = 1
  final val RANDOMSTATE_FIELD_NUMBER = 2
  @transient
  private[models] val _typemapper_randomState: _root_.scalapb.TypeMapper[_root_.com.google.protobuf.ByteString, coop.rchain.crypto.hash.Blake2b512Random] = implicitly[_root_.scalapb.TypeMapper[_root_.com.google.protobuf.ByteString, coop.rchain.crypto.hash.Blake2b512Random]]
  def of(
    pars: _root_.scala.Seq[coop.rchain.models.Par],
    randomState: coop.rchain.crypto.hash.Blake2b512Random
  ): _root_.coop.rchain.models.ListParWithRandom = _root_.coop.rchain.models.ListParWithRandom(
    pars,
    randomState
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[ListParWithRandom])
}
